### ISSUE TITLE
BUG: Omniflix denom query not working for IBC transferred denoms

### ISSUE THREAD

**Issue by gjermundgaraba** [game-of-nfts/gon-evidence#188]
The scope of bugs are not 100% clear, so not sure if this qualifies as a bug in the program or not. If not I will file it with Omniflix directly.

## Summary of Bug

When using the following command with the OmniFlix cli, there is some validation of the "ID" that is not taking IBC-denoms into account:
```shell
$ omniflixhubd q onft denom ibc/A7E0CED936458907B4A7635B0E2A63F540A84FE45C36C96CEC106D8D47C2D743
Error: invalid denom ID ibc/A7E0CED936458907B4A7635B0E2A63F540A84FE45C36C96CEC106D8D47C2D743, only accepts alphanumeric characters, and begin with an english letter: invalid denom
```

Interestingly enough, it works fine if you query using `collection` instead of `denom`.

## Environment

- OS: Linux, Ubuntu 22.04
- Software version: omniflixhubd 0.9.0-gon-test

## Steps to Reproduce

1. Transfer an NFT to OmniFlix
2. Find the class hash (`q nft-transfer class-hash`)
3. Query for denom using the form `ibc/<CLASS_HASH>`

Another approach you can take is to query for all denoms, find any that has the ibc/<CLASS_HASH> format and try to query for that one directly (which will also fail).

## Expected and Actual Behavior

It should see the format as valid and query for the IBC-transferred NFT.

**Comment by harish551** [comment]
Hey @gjermundgaraba 

can you use the latest version binary 

`v0.9.0-gon-test2`

**Comment by gjermundgaraba** [comment]
@harish551 that does indeed work. That version is however not the version in the instructions.

**Comment by harish551** [comment]
@gjermundgaraba Yes we forgot to update latest version in the docs.
(I thought it would be okay as query issues are fixed in the rpc node you are using but this validation happens directly in the binary so we should definitely update to new version )

**Comment by taramakage** [comment]
I think this issue should have been resolved by now.
