### ISSUE TITLE
BUG: Wrong transaction log for failed transaction for A6 tasks (Transfer the NFT on Uptick to IRISnet)

### ISSUE THREAD

**Issue by oldcatv** [game-of-nfts/gon-evidence#223]
## Summary of Bug

A "success" status was returned for failed transfer of NFT from Uptick to IRISNet.

There happened an occasion that "success" was returned for a failed transfer. The NFT was not transferred but a "success" status was returned by mistake.
The hash on Uptick is "46ED6726AD4A8DD96153D45771B099289F7AEF6886D44C2C844ADBDD610B7936" 
The transfer is finally completed in transaction with hash "A01AF11CE35EB7405DB13B767F89D79D834DCC5816EF38C918CF69E97FCD832B"
which returned "success" 

## Environment

- OS: Ubuntu 22.04 TLS
- Software version: Uptickd v0.2.6

## Steps to Reproduce

Have tried to reproduce the issue using the exact same commands used: 
1. Sending the same NFT from IRISNet to Uptick  
(iris tx nft-transfer transfer nft-transfer channel-17 uptick1j2u7fnhw8yjv8m6gyts08pu292ylvsnn3sg8je ocv1 ocvnft02 --from key --fees 2000uiris)
=> a successful status returned

2. Checking NFT was gone 
(iris q nft owner iaa19705lg3d7p3gyzt77hq4jhdj0sf9594crv5enx)
=> sent NFT was not found as expected

3. Sending the same NFT from Uptick back to IRISNet
uptickd tx nft-transfer transfer nft-transfer channel-3 iaa19705lg3d7p3gyzt77hq4jhdj0sf9594crv5enx ibc/F4788C5394F4CB878995DDC93DE4EF75C3BE038560C5649788D78134AB625BA9 ocvnft02 --from key
=> a successful status returned

4. Checking NFT was returned 
(iris q nft owner iaa19705lg3d7p3gyzt77hq4jhdj0sf9594crv5enx)
=> set NFT was returned as expected

5. Trigger the same command to send the same NFT from Uptick back to IRISNet 
uptickd tx nft-transfer transfer nft-transfer channel-3 iaa19705lg3d7p3gyzt77hq4jhdj0sf9594crv5enx ibc/F4788C5394F4CB878995DDC93DE4EF75C3BE038560C5649788D78134AB625BA9 ocvnft02 --from key
=> a failed status returned

However, this time the transfers are successful and smooth. The error could not be reproduced.

## Expected and Actual Behavior

N/A

## Error Stack

N/A

## Additional Context

By comparing The transaction log for the found "failed" transfer and a normal one, they are very similar.

**Comment by taramakage** [comment]
The success of an IBC transaction refers to the successful delivery of the IBC packet, not the successful execution of the functionality logic.
