### ISSUE TITLE
BUG: redundant result entries in `omniflixhubd query onft denoms`

### ISSUE THREAD

**Issue by taitruong** [game-of-nfts/gon-evidence#255]
## Summary of Bug

Doing a query on all denoms. Output contains redundant denom entries

## Environment

- OS: Ubuntu 22.04
- Software version: Omniflix v0.9.0-gon-test2

## Steps to Reproduce

```sh
$ omniflixhubd version
0.9.0-gon-test2

$ omniflixhubd query onft denoms --output text --page 0|grep "id:" >  denoms.json 
$ omniflixhubd query onft denoms --output text --page 1|grep "id:" >>  denoms.json 
$ omniflixhubd query onft denoms --output text --page 2|grep "id:" >>  denoms.json 

```

Now in file there these redundant denoms:
- ibc/FB13EEAA22AEC96A38CE92959DB492B7A487B74151EBA5AA2F3E1A9AA10BA9E3
- ibc/3031998311B73DA46F63D9CF6F55E5378C018D668DE97BCDC82B3DF88CC009AD

## Expected and Actual Behavior

A list of unique denoms, instead it outputs redundant denoms

**Comment by taitruong** [comment]
[denoms.zip](https://github.com/game-of-nfts/gon-evidence/files/10885693/denoms.zip)

**Comment by harish551** [comment]
hey @taitruong 

in above queries for page flag default number is 1 there is no 0th page 
even for --page 0 by default it's showing 1st page

can you check with --page 1, --page 2, --page 3 and check for redundant ?

**Comment by taitruong** [comment]
Ok, thx. My bad.
