### ISSUE TITLE
AWARD: TC Network Claim 2

### ISSUE THREAD

**Issue by trulacgc-tcnetwork** [game-of-nfts/gon-evidence#293]
[TC Network](https://tcnetwork.io) provides Explorer/Dashboard for the Game of NFT which allows users:

- Connect wallet: Keplr, MM
- View detail of the transaction (ex: https://gon.tcnetwork.io/juno/transaction/[txHash>])
- NFT IBC transfer by UI, this is in progress.

URL of Explorer: [Game of NFT Explorer](https://gon.tcnetwork.io)

**Comment by sienrik15** [comment]
is the source public, can i use it ?
