### ISSUE TITLE
BUG: `iris` cli, queries does not consider `output` in config in `client.toml`

### ISSUE THREAD

**Issue by taitruong** [game-of-nfts/gon-evidence#304]
## Summary of Bug

Output has been changed to `json` using `iris config output json`. But for queries like `iris query bank balances` or `iris query nft collection` output is always text. But for commands like `iris tx nft mint` it works fine and use the config for output.

## Environment

- OS: Ubuntu 22.04
- Software version: iris v1.4.1-gon-testnet

## Steps to Reproduce

```sh
# change output to json
iris config output json
# query balances
iris query bank balances MY_WALLET # output in text! but should be json!
iris query bank balances MY_WALLET --output json # output in json
# query collection
iris query nft collection 'arkprotocol001' # output in text! but should be json!
iris query nft collection 'arkprotocol001' --output json # output in json!
# mint, output in JSON
iris tx nft mint 'arkprotocol001' 'arkNFT014' --from MY_WALLET --recipient MY_WALLET --fees 2000uiris -b sync --yes
# change output to text and mint outputs to text!
iris config output text
iris tx nft mint 'arkprotocol001' 'arkNFT015' --from MY_WALLET --recipient MY_WALLET --fees 2000uiris -b sync --yes

```

## Expected and Actual Behavior

Expecting output to be based on client.toml / config!

**Comment by taramakage** [comment]
This problem has been fixed in [irismod#329](https://github.com/irisnet/irismod/pull/329)
