### ISSUE TITLE
BUG: NFT transfer from omniflix to IRISnet delayed or not happening

### ISSUE THREAD

**Issue by blasmorkai** [game-of-nfts/gon-evidence#311]
**## Summary of Bug**

 When sending back an NFT from Omniflix to IrisNET, we have experienced that the NFT either gets back with a big delay or the ownership of the NFT is not transferred from the escrow to the destination address.

**## Environment**

- OS: Any
- Software version: Any

**## Steps to Reproduce**
1.- Create collection on IrisNET
2.- Send NFT from IrisNET to Omniflix
3.- Transfer back from Omniflix to Irisnet
omniflixhubd tx nft-transfer transfer nft-transfer channel-24 iaa1m8juq54rm6tar0nkf50m436u66mlf8y7sx0x8w ibc/8538CEDC73F1063C104607F5457D0F5A3649E18FC4ECF57A7A76EF8636547DB4 token002 --gas auto --gas-adjustment 1.5 --gas-prices 0.025uflix --from BMWallet --node http://65.21.93.56:26657 --chain-id gon-flixnet-1
_**-->CASE 1: NFT HAS NOT BEEN TRANSFERRED FROM ESCROW TO OWNER**_
TxHash	40FD09ECFC47ECA0D4997FA9A829595B7FE7E62DD4E92BE7EAA2BAE6E18472A7 

omniflixhubd tx nft-transfer transfer nft-transfer channel-24 iaa1m8juq54rm6tar0nkf50m436u66mlf8y7sx0x8w ibc/8538CEDC73F1063C104607F5457D0F5A3649E18FC4ECF57A7A76EF8636547DB4 token003 --gas auto --gas-adjustment 1.5 --gas-prices 0.025uflix --from BMWallet --node http://65.21.93.56:26657 --chain-id gon-flixnet-1
**_-->CASE 2: TOOK A LONG TIME TO TRANSFER NFT FROM ESCROW TO OWNER_**
TxHast 7FE8143DDF01113E6FFF24D43C512AA0DD2C8D724A8E529B7C9B85FE7F38F0AC 

4.- Query collection on Irisnet, the NFT is not transferred back to owner on IrisNET or transferred after a long delay.
omniflixhubd query onft collection ibc/8538CEDC73F1063C104607F5457D0F5A3649E18FC4ECF57A7A76EF8636547DB4
iris query nft collection workshop

**## Expected and Actual Behavior**

Actual: NFT either arrives late or does not arrive. 
Preferred: NFT should arrive in less than 3 minutes to the destination account.

**## Error Stack**

No noticable errors.

**## Additional Context**

Sunday 5/3/2023, around 20:00 UTC.

**Comment by taramakage** [comment]
This is a relayer problem where it became stuck with many transactions.
