### ISSUE TITLE
AWARD: Exclusive nominee Community Star 

### ISSUE THREAD

**Issue by Exclusive048** [game-of-nfts/gon-evidence#336]
**SUMMARY**
_I decided to aggregate information that will be useful for testing. As the tasks are completed, I will supplement this topic._
### So, let's begin:
**1. Setting config, for example IRIS:**
```
$ iris config
{
        "chain-id": "gon-irishub-1",
        "keyring-backend": "os",
        "output": "json",
        "node": "http://34.80.93.133:26657",
        "broadcast-mode": "sync"
}
```
 I suggest setting as a minimum node and chain-id. 
```
iris config node <node>
iris config chain-id <chain-id>
```
Also better setting broadcast-mode to sync. This way it only waits until TX is returned. using block leads often client to timeout after a certain limit - which doesn't mean command is not executed... just don't use async otherwise you won't get a tx.
Since output is sometimes very long. You can output to json and use jq in bash for better formatting. With jq you can easily also query elements in json.

**2. Uptick GON Explorer**
I did not find information about the Uptick browser, so I will write it down here: https://explorer.testnet.uptick.network/

**3.Useful linkfor Decode/Encode Base64 format (Necessary for payload message).**
https://www.base64encode.org/

### Utility
I want to leave a probably useful link for those who want to save their time writing transactions.
Let's say thanks to the participants of testnet`a, although I personally do not use it, it will probably be useful to someone.
http://gon.disperze.com/ibc-transfer

### Help for participants
I also worked for the benefit of test participants by helping them with the following(Some members contacted DM):
1. Help with commands
2. Help with the particular details of the challenges
3. Help with NFT token tracing.

**Comment by taramakage** [comment]
Could you please seperate this claim into two issue?
