### ISSUE TITLE
Bug: Multiple nft cross-chain transactions

### ISSUE THREAD

**Issue by ElfenLied2019** [game-of-nfts/gon-evidence#359]
Cross-chain an nft from uptick to iris, and generate a transaction record on uptick. Correspondingly, a cross-chain record will be generated in iris. But now there are many cross-chain records on iris.

uptick nft denom id : notSet
uptick nft token id : multx16
uptick ibc txid: BE089C574C182D5E3DCD445BBCAF305B8D32E20B5C034EF0B75D12ADCC51BF19

iris nft denom id: ibc/E58F5FEFD89F869F9AE2341448867E4AFAECE456AE7146F2FFD5BBC50969C154
iris nft  token id : multx16
iris  ibc txid :
txid: 74F6289C34C0E4E659482C12A29E653B220BAD05E194A8721832FA2B55571F7A  height: 378521
txid: 70A605EE8AFE618C3047FC7A6FD2C8F2FF8D7DB15D8820F989594AB198C0B88E  height: 378521
txid: 88D6E49604EC07C4E0C5C50F52C8789C16F1B8B8B8AD7F0A3EA62CBA19B99341  height: 378521
txid: 694869FBEB58318DCA0EAC44C28F60E94FF64B7F6022286E3806EA545B53594A  height: 378520
txid: 9085719F2C9F8AE9CD238E33207EDB28D5DE850B6F62F2C8D8E49C57E417F200  height: 378520
txid: F28162F44A9F280AE04B1A3552353CF8CAF72951B50F7991E058BD259866BA8F  height: 378520

Refer to: http://34.80.93.133:1317/cosmos/tx/v1beta1/txs?events=recv_packet.packet_sequence%3D%27172%27&events=recv_packet.packet_src_channel%3D%27channel-3%27&events=recv_packet.packet_dst_channel%3D%27channel-17%27&pagination.reverse=false&limit=10&page=1

**Comment by taramakage** [comment]
This problem has been fixed in [irishub#2812](https://github.com/irisnet/irishub/pull/2812)
