### ISSUE TITLE
AWARD: JS-Team Claim 2

### ISSUE THREAD

**Issue by ShenFri** [game-of-nfts/gon-evidence#404]
JS-Team provides NFT path visualization tools/ Explorer  for the Game of NFT :

- Query by TXID

- Query by Address

- Analyze NFT path by classID

URL of Explorer: http://www.nftland.org/

**Comment by JakeHartnell** [comment]
Is this open source?

**Comment by shanev** [comment]
Are there screenshots of this in action?
