### ISSUE TITLE
AWARD: EmpowerChain Claim 2: GoN CLI

### ISSUE THREAD

**Issue by gjermundgaraba** [game-of-nfts/gon-evidence#412]
I have made an easy-to-use, interactive CLI that lets people easily work with NFTs in the interchain. It does not require the user to learn a bunch of commands and flags to operate it. Everything is there.

It has a wide range of features for both regular operations of NFTs as well as debugging of IBC transactions. 

I have consistently been pushing out new releases with new features depending on the tasks we are doing, and the issues I see people in the community are having. A good example of this is IBC transaction debugging which people struggle to understand. I visualize and explain them so you understand that there are multiple transactions involved.

![gon-nft-transfer-ibc-wait](https://user-images.githubusercontent.com/1344105/224550571-22c14db5-5a8f-4b89-bba8-8405f3ad3da2.gif)

The main features are:
- Create class/denom 
- Mint NFTs
- Query NFTs
- Transfer NFTs over IBC (and it waits for IBC to complete on both chains)
  - Extra feature: [Self relay!](https://github.com/gjermundgaraba/gon-tools/blob/main/gon-cli/self-relay.md) 

In addition I have develop a range of helper/debugging tools:
- `evidence.xslx` format validation
- Finding IBC transactions (including timeout tranasctions)
- List connections between any two chains (in GoN)
- Key management
- Query transactions
- Calculate class-hash (without the class-hash having to be present on any chain)
- Generate a class trace (by selecting all hops it generates out a full class trace - useful for finding a class id on CosmWasm chains)
- Self-relay stuck messages (either by forcing the timeout transaction, or actually relaying the message) by only having the inital Tx hash

The code is open source: https://github.com/gjermundgaraba/gon-tools

(There is also a small environment variable script in the repo to make using the native CLI's directly easier too)

**Comment by Exclusive048** [comment]
Hello
Please pay attention. Probably an error in the block definition for the timeout.

https://github.com/game-of-nfts/gon-evidence/issues/420

**Comment by gjermundgaraba** [comment]
The issue reported above turned out to be related to the congested channels. The GoN CLI has in any case since then added two features to make this problem go away entierly:
1: Make IBC timeouts more resilient
2: Added the ability to _self relay_ messages directly with the CLI, entierly bypassing the queue in the packed channels!
