### ISSUE TITLE
Possible error related to timeout

### ISSUE THREAD

**Issue by Exclusive048** [game-of-nfts/gon-evidence#420]
A certain user 0xtekgrinder#1558 used the **gon cli** service and sent a transaction from Juno to Iris.
Transaction hash: `94E6EA52C5B3EC73B407D6C45CA6D7B0C5E335920CC218B1E59E10EB9D3C9896`
It got an error: `rpc error: code = NotFound desc = packet acknowledgment hash not found: key not found`

After a little analysis, I saw that it was the height of the block specified in the encoded message:
`ewogICJyZWNlaXZlciI6ICJpYWExZDk1NzhreHA4ZnUwYXo4MDk4ZDJyOXd6bnFmcjBud3d1dW1tOGUiLAogICJjaGFubmVsX2lkIjogImNoYW5uZWwtOTAiLAogICJ0aW1lb3V0IjogewogICAgImJsb2NrIjogewogICAgICAicmV2aXNpb24iOiAxLAogICAgICAiaGVpZ2h0IjogNDE2NzA2CiAgICB9CiAgfQp9`
The message is the following:
```
{
  "receiver": "iaa1d9578kxp8fu0az8098d2r9wznqfr0nwwuumm8e",
  "channel_id": "channel-90",
  "timeout": {
    "block": {
      "revision": 1,
      "height": 416706
    }
  }
}
```

But the transaction was executed in a much higher block. See screenshot:
![image](https://user-images.githubusercontent.com/22451005/224562542-4780975e-5d3e-4446-bd81-20130395beb1.png)

Perhaps this is not a bug, or a service error.
But as far as I know, timeout related errors look different.
This confused both me and the participant.
Please pay attention to this.
If this is a service error, please explain why such an error occurred and what exactly it means.

Thank you for your attention :)

P.S.
The discussion took place in the gon-testnet channel

**Comment by gjermundgaraba** [comment]
The main problem in this case was that the timeout transaction had not been picked up and committed back to Juno - so it appeared to be gone.
Running the relayer on that channel fixed the problem.

I think the reason the height was wrong here (and therefore caused a timeout) was because no relayer was running and updating the client. When the client is not updated, the height will be wrong. But the worst that should happen is a timeout. And that is also what happened. 

So all in all, pretty sure this is just a lack of relayers running

**Comment by giansalex** [comment]
the solution is to use timestamp, or timeout-height but taking as base the latest height from remote chain.

**Comment by Exclusive048** [comment]
> the solution is to use timestamp, or timeout-height but taking as base the latest height from remote chain.


I didn't need a solution.
I did not understand the very essence of the error and the reason for its occurrence.

**Comment by giansalex** [comment]
@Exclusive048 That error does not come from the transaction, you should check in GoN cli repo

**Comment by Exclusive048** [comment]
@giansalex , In this case, I suggest participants not to use the service, so as not to waste their time.

**Comment by gjermundgaraba** [comment]
> @giansalex , In this case, I suggest participants not to use the service, so as not to waste their time.

That won't help much, as the main problem here is that the channel is filled up with 350,000 transactions. The cli works just fine, but transactions are going to time out in most cases anyway.
