### ISSUE TITLE
BUG: Cannot get <class-hash> from correct <nft-transfer-trace>

### ISSUE THREAD

**Issue by yuanzd123** [game-of-nfts/gon-evidence#494]
## Summary of Bug
 Cannot get <class-hash> from correct <nft-transfer-trace> using command:
`junod q wasm contract-state smart juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a '{"nft_contract": {"class_id" : "wasm.juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a/channel-120/wasm.stars1ve46fjrhcrum94c7d8yc2wsdz8cpuw73503e8qn9r44spr6dw0lsvmvtqh/channel-207/supermintG"}}'`

## Environment

- OS: macOS 13.2.1 (22D68)
- Software version: v12.0.0

## Steps to Reproduce

This happens when I transfer NFT following this flow: i --(1)--> s --(1)--> j --(1)

The following channel is deprecated and the transaction may fail:
wasm.stars1ve46fjrhcrum94c7d8yc2wsdz8cpuw73503e8qn9r44spr6dw0lsvmvtqh/channel-211 <> wasm.juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a/channel-93
Therefore I am using the new channel
wasm.stars1ve46fjrhcrum94c7d8yc2wsdz8cpuw73503e8qn9r44spr6dw0lsvmvtqh/channel-230 <> wasm.juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a/channel-120

Transaction hash:
i --(1)--> s --(1): `9E8F18E127CA44B9002472712E6D969A5B0E6AB407A193950B8ED3F19541F35D`
s --(1)--> j --(1): `A5CCA2462B680A476D86A1486F2B5EF5FBB34FACAEC120023580DD83D8A72162`

## Expected and Actual Behavior

It should return a class-hash. It returns null. 

## Additional Context

I have checked others transfer from the old channel are working correctly.
For example, 
`junod q wasm contract-state smart juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a '{"nft_contract": {"class_id" : "wasm.juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a/channel-93/wasm.stars1ve46fjrhcrum94c7d8yc2wsdz8cpuw73503e8qn9r44spr6dw0lsvmvtqh/channel-207/a2001"}}'
`
returns `juno18wmuflvdm7klx06js8tq0hhadmhxj65qxg2nncgj8u5z08cus0psk2kp9p`

**Comment by gjermundgaraba** [comment]
What are you expecting the output to be?

When I run the command it appears to work just fine:
```bash
$ junod q wasm contract-state smart juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a '{"nft_contract": {"class_id" : "wasm.juno1stv6sk0mvku34fj2mqrlyru6683866n306mfv52tlugtl322zmks26kg7a/channel-120/wasm.stars1ve46fjrhcrum94c7d8yc2wsdz8cpuw73503e8qn9r44spr6dw0lsvmvtqh/channel-207/supermintG"}}'
data: juno1mmwccyvcnnh7fv6agndxmdkpk0kgptppm436gxgeuwk75eh9dpwqxx3jv9
```

**Comment by gjermundgaraba** [comment]
It might have just not have been relayed over yet
