### ISSUE TITLE
BUG:Reason for contract error in nft from cosmos chain to wasm nft

### ISSUE THREAD

**Issue by ElfenLied2019** [game-of-nfts/gon-evidence#535]
In NFT cross chain transactions from Uptick, Irihub, and Omniflixhub to Stargaze, Juno, the parameter "revision_height" will be automatically obtained when creating cross chain transactions, but the obtained "revision_height" is smaller than the actual value. One party successfully trades but the other party does not receive it, resulting in NFT being in a managed state all the time.

For example, NFT cross chain from Omniflixhub to Juno。 txid: EE3F6EE8E874B633C0985C3265995394E137C94A543B6914DA870F177E7F2AB, the transaction creation time is 2023-03-17T01:57:37Z, and the value of the parameter "revision_height" is 565953, but in the Juno chain, the time for the height of 565953 is 2023-03-15T18:00:35.071266717Z. The timeout for ibc transactions is significantly shorter than the current time,

https://gon.ping.pub/omniflix/tx/EE3F6EE8E874B633C0985C32659953942E137C94A543B6914DA870F177E7F2AB
<img width="1142" alt="图片" src="https://user-images.githubusercontent.com/49516229/225838641-b9033e52-47c1-4734-b817-fc9e6fb8d61b.png">

https://gon.ping.pub/juno/blocks/565953
<img width="1209" alt="图片" src="https://user-images.githubusercontent.com/49516229/225838915-0f5d8cfc-af2f-4eed-a730-c881b376eddb.png">

There are also similar cases：

Irishub to Juno txid:95A22293F62C7387DEF2A5ADC231F347D68920BA5151D28641117C8559DB98A5
uptick to Juno txid:343636B2361DDA92303AB318FE0CE39C5D997FB0E469BBA15FBDB408E748741F

**Comment by giansalex** [comment]
this is a problem in the client used, you could add the flag `--packet-timeout-height 0-0`, to use timestamp as timeout.

The dates you are comparing are in different formats (1. your time zone, 2. UTC). the difference is aprox 2 hours

**Comment by taramakage** [comment]
This is a median time issue in blockchain. The timestamp is the middle time of all nodes, so it may deviate from the actual time.
