### ISSUE TITLE
AWARD: S16 Research Ventures Claim 2

### ISSUE THREAD

**Issue by arifintahu** [game-of-nfts/gon-evidence#698]
S16 Research Ventures provides a GUI for searching Collection ID on all GoN Chains and showing its NFTS.

URL: [https://gon-collections.s16.online](https://gon-collections.s16.online)

Snapshots:

![image](https://user-images.githubusercontent.com/20294658/227111443-10c88b2f-26ce-411b-a2a1-8ec656989d70.png)
![image](https://user-images.githubusercontent.com/20294658/227111576-358e254a-0c8e-428a-a036-77de59ff5cf1.png)

**Comment by JakeHartnell** [comment]
Is this open source?

**Comment by arifintahu** [comment]
> Is this open source?

sure you can access here https://github.com/arifintahu/gon-showcase
