### ISSUE TITLE
AWARD: Stakeflow Claim 2

### ISSUE THREAD

**Issue by i7495** [game-of-nfts/gon-evidence#813]
**[Stakeflow](https://stakeflow.io)** team has updated our explorer for the Game of NFTs which now allows users to explore the Cosmos NFT ecosystem. For each of the 5 networks, a comprehensive catalog of collections (Native and IBC) is provided, allowing users to search and view the content within these collections:

- [IRISnet NFT collections dashboard](https://stakeflow.io/irisnet-game-of-nfts/nft-collections)
- [OmniFlix NFT collections dashboard](https://stakeflow.io/omniflix-game-of-nfts/nft-collections)
- [Uptick NFT collections dashboard](https://stakeflow.io/uptick-game-of-nfts/nft-collections)
- [Stargaze NFT collections dashboard](https://stakeflow.io/stargaze-game-of-nfts/nft-collections)
- [Juno NFT collections dashboard](https://stakeflow.io/juno-game-of-nfts/nft-collections)

![StakeflowNFT2](https://user-images.githubusercontent.com/35506765/227795747-09f447bd-cff4-4a38-a20b-e4fd302a297c.gif)

Additionally, by inputting any address into the search box, you can view collections containing NFTs associated with that specific address.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35506765/227790956-62d0d4ac-7b41-4aee-a530-572e216b8c06.png">

On the [account profile page](https://stakeflow.io/irisnet-game-of-nfts/accounts/iaa16hf2amez7xs44cvyz3wh2xdx0tfmepq8zhl3jc), you can also view all NFTs associated with an address as well as other relevant account information.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35506765/227791062-811ed4ae-bafe-470c-8d46-ec40ff2b81ed.png">

In addition, the explorer contains a lot of other information on supported networks.

**Comment by JakeHartnell** [comment]
Is this open source?
